FROM postgres:15

# Add custom configuration
COPY ./postgres/init.sql /docker-entrypoint-initdb.d/
COPY ./postgres/postgresql.conf /etc/postgresql/postgresql.conf

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=home_library

# Expose port
EXPOSE 5432

# Use custom configuration
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"] 